version: '3.7'
services:
  apollo:
    container_name: apollo
    build:
      context: ./apollo
      dockerfile: Dockerfile
    volumes:
      - ./apollo/src:/app/src
    ports:
      - 4000:4000

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
